Add OpenShift template with OAuth 2.0 authentication
raffaelespazzoli/kube-ops-view pull request #1
Opened 2018-05-04 11:58 UTC by bliemli

2018-05-04 14:29 UTC, raffaelespazzoli commented on deploy-openshift/kube-ops-view-oauth.yaml
> +    value: kube-ops-view.example.com
can you make this value mandatory by removing the default (which is not going to be valid in most cases anyway). So the user will have to think about what they want here.

2018-05-04 14:31 UTC, raffaelespazzoli requested changes

2018-05-04 14:31 UTC, raffaelespazzoli commented on deploy-openshift/kube-ops-view-oauth.yaml
> +    value: kube-ops-view.example.com
can you make this value mandatory by removing the default (which is not going to be valid in most cases anyway). So the user will have to think about what they want here.

2018-05-07 09:31 UTC, bliemli commented
I removed the default value but provided the example URL in the description so the user knows what the expected format looks like.

2018-05-07 12:15 UTC, raffaelespazzoli commented
@bliemli thanks for your contribution.
I am going to accept the PR.
However I think we could improve the user experience of using the template.
1. the KUBE_OPS_APP_VIEW_DOMAIN should be required.
2. the client id and secret I believe can be auto-generated. If not please specify in the doc how they should be created.
would you be willing to create an new PR with these changes?

2018-05-07 12:15 UTC, merged

2018-05-07 14:44 UTC, bliemli commented
@raffaelespazzoli Thank you for merging my PR.

> 1. the KUBE_OPS_APP_VIEW_DOMAIN should be required.

This environment variable is not required intentionally. If the template is instantiated without it the route should be created using the default naming scheme of something like <appname>-<projectname>.<default-appdomain> (I don't remember it exactly).

> 2. the client id and secret I believe can be auto-generated. If not please specify in the doc how they should be created.

The client ID and secret have to be created on the OAuth server side, e.g. Keycloak and can't be generated on the client side. I'm going to clarify this in the variables' description.